[project]
name = "opencv4-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "caer>=2.1.1",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "opencv-contrib-python>=4.11.0.86",
]
